services:
  web:
    build:
      context: ./web
    container_name: web_service
    ports:
      - "8080:8081"
    depends_on:
      - db
      - redis

  worker:
    build:
      context: ./worker
    container_name: worker_service
    depends_on:
      - redis

  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis_queue
    ports:
      - "6379:6379"

volumes:
  db_data:
