version: '3.8'

services:
  web:
    build: ./web
    command: >
      sh -c "pytest --junitxml=results.xml --cov=. --cov-report=xml"

    ports:
      - "5000:5000"
    volumes:
      - ./web:/app
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - worker

  worker:
    build: ./worker
    command: >
      sh -c "pytest --junitxml=results.xml --cov=. --cov-report=xml"
    volumes:
      - ./worker:/app
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis

  redis:
    image: redis:6
    ports:
      - "6379:6379"
